#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleScion-import-private.h
src/reflect/_MulleScion-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleScion-import.h
src/reflect/_MulleScion-include.h
)

set( PUBLIC_HEADERS
src/MulleCommonObjCRuntime.h
src/MulleMutableLineNumber.h
src/MulleObjCCompilerSettings.h
src/MulleObjCLoader+MulleScion.h
src/MulleScionDataSourceProtocol.h
src/MulleScionNull.h
src/MulleScionObjectModel+BlockExpansion.h
src/MulleScionObjectModel+MacroExpansion.h
src/MulleScionObjectModel+NSCoding.h
src/MulleScionObjectModel+Parsing.h
src/MulleScionObjectModel+Printing.h
src/MulleScionObjectModel+TraceDescription.h
src/MulleScionObjectModel.h
src/MulleScionOutputProtocol.h
src/MulleScionParser+Parsing.h
src/MulleScionParser.h
src/MulleScionPrinter.h
src/MulleScionPrintingException.h
src/MulleScionTemplate+CompressedArchive.h
src/MulleScion.h
src/NSFileHandle+MulleOutputFileHandle.h
src/NSObject+KVC_Compatibility.h
src/NSObject+MulleScionDescription.h
src/NSString+MulleScion.h
src/import.h
src/include.h
)

