# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleScion-import-private.h
src/reflect/_MulleScion-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/import-private.h
src/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleScion-export.h
src/reflect/_MulleScion-import.h
src/reflect/_MulleScion-include.h
src/reflect/_MulleScion-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/import.h
src/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/MulleCommonObjCRuntime.h
src/MulleMutableLineNumber.h
src/MulleObjCCompilerSettings.h
src/MulleObjCLoader+MulleScion.h
src/MulleScionDataSourceProtocol.h
src/MulleScionNull.h
src/MulleScionObjectModel+BlockExpansion.h
src/MulleScionObjectModel+MacroExpansion.h
src/MulleScionObjectModel+NSCoding.h
src/MulleScionObjectModel+Parsing.h
src/MulleScionObjectModel+Printing.h
src/MulleScionObjectModel+TraceDescription.h
src/MulleScionObjectModel.h
src/MulleScionOutputProtocol.h
src/MulleScionParser+Parsing.h
src/MulleScionParser.h
src/MulleScionPrinter.h
src/MulleScionPrintingException.h
src/MulleScionTemplate+CompressedArchive.h
src/MulleScion.h
src/NSFileHandle+MulleOutputFileHandle.h
src/NSObject+KVC_Compatibility.h
src/NSObject+MulleScionDescription.h
src/NSString+MulleScion.h
)

