#
# This file will be included by cmake/share/resources.cmake
#
# cmake/reflect/_Resources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-resource--resources
#
set( RESOURCES
src/MulleScion-Info.plist
)
