# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleMutableLineNumber.m
src/MulleScionDataSourceProtocol.m
src/MulleScionLocals.m
src/MulleScionNull.m
src/MulleScionObjectModel+BlockExpansion.m
src/MulleScionObjectModel+Graphviz.m
src/MulleScionObjectModel+MacroExpansion.m
src/MulleScionObjectModel+NSCoding.m
src/MulleScionObjectModel+Parsing.m
src/MulleScionObjectModel+Printing.m
src/MulleScionObjectModel+TraceDescription.m
src/MulleScionObjectModel.m
src/MulleScionParser+Parsing.m
src/MulleScionParser.m
src/MulleScionPrinter.m
src/MulleScionPrintingException.m
src/MulleScionTemplate+CompressedArchive.m
src/MulleScion.m
src/NSFileHandle+MulleOutputFileHandle.m
src/NSObject+KVC_Compatibility.m
src/NSObject+MulleScionDescription.m
src/NSString+MulleScion.m
src/NSValue+CheatAndHack.m
src/exists.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleScion.m
)
