/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleScion_import_h__
#define _MulleScion_import_h__

// How to tweak the following MulleFoundation #import
//    remove:          `mulle-sourcetree mark MulleFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleFoundation no-os-<osname>`
# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// How to tweak the following MulleObjCHTTPFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCHTTPFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCHTTPFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCHTTPFoundation no-os-<osname>`
# import <MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>   // MulleObjCHTTPFoundation

// How to tweak the following MulleObjCInetOSFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCInetOSFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCInetOSFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCInetOSFoundation no-os-<osname>`
# import <MulleObjCInetOSFoundation/MulleObjCInetOSFoundation.h>   // MulleObjCInetOSFoundation

#include "_MulleScion-include.h"


#endif
