/*
 *   This file will be regenerated by `mulle-bash`.
 *   Any edits will be lost.
 */
#if defined( MULLE_FOUNDATION_VERSION)
# if MULLE_FOUNDATION_VERSION < ((0 << 20) | (21 << 8) | 1)
#  error "MulleFoundation is too old"
# endif
# if MULLE_FOUNDATION_VERSION >= ((0 << 20) | (22 << 8) | 0)
#  error "MulleFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_HTTP_FOUNDATION_VERSION)
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 4)
#  error "MulleObjCHTTPFoundation is too old"
# endif
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCHTTPFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_INET_OS_FOUNDATION_VERSION)
# if MULLE_OBJC_INET_OS_FOUNDATION_VERSION < ((0 << 20) | (20 << 8) | 2)
#  error "MulleObjCInetOSFoundation is too old"
# endif
# if MULLE_OBJC_INET_OS_FOUNDATION_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "MulleObjCInetOSFoundation is too new"
# endif
#endif
